-- Inserir produtos Queen (158x198) - Categoria: Colchões

INSERT INTO products (name, medida, categoria, quantidade, estoqueMinimo, precoCusto, precoVenda, createdAt, updatedAt) VALUES
('BRAVISSIMO', 'Queen', 'Colchões', 1, 2, NULL, NULL, NOW(), NOW()),
('ADAPTO', 'Queen', 'Colchões', 1, 2, NULL, NULL, NOW(), NOW()),
('ALVA', 'Queen', 'Colchões', 3, 2, NULL, NULL, NOW(), NOW()),
('CRYSTAL', 'Queen', 'Colchões', 1, 2, NULL, NULL, NOW(), NOW()),
('DIAMOND', 'Queen', 'Colchões', 1, 2, NULL, NULL, NOW(), NOW()),
('XL FIRME', 'Queen', 'Colchões', 2, 2, NULL, NULL, NOW(), NOW()),
('BLEND', 'Queen', 'Colchões', 1, 2, NULL, NULL, NOW(), NOW()),
('COMFY', 'Queen', 'Colchões', 2, 2, NULL, NULL, NOW(), NOW()),
('JOY', 'Queen', 'Colchões', 0, 2, NULL, NULL, NOW(), NOW()),
('ESMERALDA', 'Queen', 'Colchões', 0, 2, NULL, NULL, NOW(), NOW()),
('LUSH', 'Queen', 'Colchões', 0, 2, NULL, NULL, NOW(), NOW()),
('GUARDA COSTA FORCE EXTREME', 'Queen', 'Colchões', 0, 2, NULL, NULL, NOW(), NOW()),
('HERVAL INSPIRACION ONE', 'Queen', 'Colchões', 1, 2, NULL, NULL, NOW(), NOW()),
('DREAM', 'Queen', 'Colchões', 0, 2, NULL, NULL, NOW(), NOW()),
('GEO', 'Queen', 'Colchões', 1, 2, NULL, NULL, NOW(), NOW()),
('CONFORT GEL', 'Queen', 'Colchões', 2, 2, NULL, NULL, NOW(), NOW()),
('SMART CLASSIC', 'Queen', 'Colchões', 1, 2, NULL, NULL, NOW(), NOW()),
('SMART MILANO', 'Queen', 'Colchões', 2, 2, NULL, NULL, NOW(), NOW()),
('SEATTLE EXTRA FIRM', 'Queen', 'Colchões', 1, 2, NULL, NULL, NOW(), NOW()),
('COL SEATLE B (TECIDO BRANCO)', 'Queen', 'Colchões', 0, 2, NULL, NULL, NOW(), NOW()),
('PHOENIX', 'Queen', 'Colchões', 1, 2, NULL, NULL, NOW(), NOW()),
('PEARL', 'Queen', 'Colchões', 6, 2, NULL, NULL, NOW(), NOW()),
('AMBER', 'Queen', 'Colchões', 4, 2, NULL, NULL, NOW(), NOW()),
('TITANIUM SIMMONS', 'Queen', 'Colchões', 0, 2, NULL, NULL, NOW(), NOW()),
('REPAIR', 'Queen', 'Colchões', 1, 2, NULL, NULL, NOW(), NOW()),
('REFORCE AMX 34CM', 'Queen', 'Colchões', 0, 2, NULL, NULL, NOW(), NOW()),
('RELAX ADORABILE', 'Queen', 'Colchões', 1, 2, NULL, NULL, NOW(), NOW()),
('WISH', 'Queen', 'Colchões', 3, 2, NULL, NULL, NOW(), NOW()),
('WIND', 'Queen', 'Colchões', 2, 2, NULL, NULL, NOW(), NOW()),
('STRESS FREE', 'Queen', 'Colchões', 0, 2, NULL, NULL, NOW(), NOW()),
('ECOLIFE', 'Queen', 'Colchões', 1, 2, NULL, NULL, NOW(), NOW()),
('KOLN', 'Queen', 'Colchões', 0, 2, NULL, NULL, NOW(), NOW()),
('CONFORT HOSPITALITTY', 'Queen', 'Colchões', 3, 2, NULL, NULL, NOW(), NOW()),
('SELECTO D45', 'Queen', 'Colchões', 0, 2, NULL, NULL, NOW(), NOW()),
('MALAGA', 'Queen', 'Colchões', 1, 2, NULL, NULL, NOW(), NOW()),
('MIAMI', 'Queen', 'Colchões', 2, 2, NULL, NULL, NOW(), NOW()),
('VIVERE', 'Queen', 'Colchões', 0, 2, NULL, NULL, NOW(), NOW()),
('PLEACE', 'Queen', 'Colchões', 4, 2, NULL, NULL, NOW(), NOW()),
('VIENA', 'Queen', 'Colchões', 2, 2, NULL, NULL, NOW(), NOW()),
('TUNGSTEM', 'Queen', 'Colchões', 2, 2, NULL, NULL, NOW(), NOW());
