-- Atualizar marcas dos produtos Queen importados
UPDATE products SET marca = 'AMERICANFLEX' WHERE name = 'BRAVISSIMO' AND medida = 'Queen';
UPDATE products SET marca = 'ECOFLEX' WHERE name = 'ADAPTO' AND medida = 'Queen';
UPDATE products SET marca = 'ECOFLEX' WHERE name = 'ALVA' AND medida = 'Queen';
UPDATE products SET marca = 'KING KOIL' WHERE name = 'CRYSTAL' AND medida = 'Queen';
UPDATE products SET marca = 'KING KOIL' WHERE name = 'DIAMOND' AND medida = 'Queen';
UPDATE products SET marca = 'KING KOIL' WHERE name = 'XL FIRME' AND medida = 'Queen';
UPDATE products SET marca = 'ECOFLEX' WHERE name = 'BLEND' AND medida = 'Queen';
UPDATE products SET marca = 'ECOFLEX' WHERE name = 'COMFY' AND medida = 'Queen';
UPDATE products SET marca = 'PLUMATEX' WHERE name = 'JOY' AND medida = 'Queen';
UPDATE products SET marca = 'PROBEL' WHERE name = 'ESMERALDA' AND medida = 'Queen';
UPDATE products SET marca = 'ECOFLEX' WHERE name = 'LUSH' AND medida = 'Queen';
UPDATE products SET marca = 'PROBEL' WHERE name = 'GUARDA COSTA FORCE EXTREME' AND medida = 'Queen';
UPDATE products SET marca = 'HERVAL' WHERE name = 'HERVAL INSPIRACION ONE' AND medida = 'Queen';
UPDATE products SET marca = 'INDUCOL' WHERE name = 'DREAM' AND medida = 'Queen';
UPDATE products SET marca = 'ECOFLEX' WHERE name = 'GEO' AND medida = 'Queen';
UPDATE products SET marca = 'PLUMATEX' WHERE name = 'CONFORT GEL' AND medida = 'Queen';
UPDATE products SET marca = 'PLUMATEX' WHERE name = 'SMART CLASSIC' AND medida = 'Queen';
UPDATE products SET marca = 'PLUMATEX' WHERE name = 'SMART MILANO' AND medida = 'Queen';
UPDATE products SET marca = 'SIMMONS' WHERE name = 'SEATTLE EXTRA FIRM' AND medida = 'Queen';
UPDATE products SET marca = 'SIMMONS' WHERE name = 'COL SEATLE B (TECIDO BRANCO)' AND medida = 'Queen';
UPDATE products SET marca = 'PLUMATEX' WHERE name = 'PHOENIX' AND medida = 'Queen';
UPDATE products SET marca = 'KING KOIL' WHERE name = 'PEARL' AND medida = 'Queen';
UPDATE products SET marca = 'KING KOIL' WHERE name = 'AMBER' AND medida = 'Queen';
UPDATE products SET marca = 'SIMMONS' WHERE name = 'TITANIUM SIMMONS' AND medida = 'Queen';
UPDATE products SET marca = 'KING KOIL' WHERE name = 'REPAIR' AND medida = 'Queen';
UPDATE products SET marca = 'AMERICANFLEX' WHERE name = 'REFORCE AMX 34CM' AND medida = 'Queen';
UPDATE products SET marca = 'ECOFLEX' WHERE name = 'RELAX ADORABILE' AND medida = 'Queen';
UPDATE products SET marca = 'INDUCOL' WHERE name = 'WISH' AND medida = 'Queen';
UPDATE products SET marca = 'INDUCOL' WHERE name = 'WIND' AND medida = 'Queen';
UPDATE products SET marca = 'PLUMATEX' WHERE name = 'STRESS FREE' AND medida = 'Queen';
UPDATE products SET marca = 'PLUMATEX' WHERE name = 'ECOLIFE' AND medida = 'Queen';
UPDATE products SET marca = 'HERVAL' WHERE name = 'KOLN' AND medida = 'Queen';
UPDATE products SET marca = 'KING KOIL' WHERE name = 'CONFORT HOSPITALITTY' AND medida = 'Queen';
UPDATE products SET marca = 'PLUMATEX' WHERE name = 'SELECTO D45' AND medida = 'Queen';
UPDATE products SET marca = 'HERVAL' WHERE name = 'MALAGA' AND medida = 'Queen';
UPDATE products SET marca = 'PLUMATEX' WHERE name = 'MIAMI' AND medida = 'Queen';
UPDATE products SET marca = 'HERVAL' WHERE name = 'VIVERE' AND medida = 'Queen';
UPDATE products SET marca = 'FLEX' WHERE name = 'PLEACE' AND medida = 'Queen';
UPDATE products SET marca = 'FLEX' WHERE name = 'VIENA' AND medida = 'Queen';
UPDATE products SET marca = 'KING KOIL' WHERE name = 'TUNGSTEM' AND medida = 'Queen';
